export const FETCH_SINGLE_ARTIST_SUCCEDED = 'FETCH_SINGLE_ARTIST_SUCCEDED';
export const FETCH_ARTIST_TOP_TRACKS_SUCCEDED =
  'FETCH_ARTIST_TOP_TRACKS_SUCCEDED';
export const FETCH_ARTIST_RELATED_ARTISTS_SUCCEDED =
  'FETCH_ARTIST_RELATED_ARTISTS_SUCCEDED';
export const LOADING_ARTIST = 'LOADING_ARTIST';
export const LOADING_ARTIST_FAILED = 'LOADING_ARTIST_FAILED';
export const LOADING_TOP_TRACKS = 'LOADING_TOP_TRACKS ';
export const LOADING_TOP_TRACKS_FAILED = 'LOADING_TOP_TRACKS_FAILED';
export const LOADING_RELATED_ARTISTS = 'LOADING_RELATED_ARTISTS';
export const LOADING_RELATED_ARTISTS_FAILED = 'LOADING_RELATED_ARTISTS_FAILED';
