export const FETCH_ALBUMS_LIST_SUCCEDED = 'FETCH_ALBUMS_LIST_SUCCEDED';
export const FETCH_SINGLE_ALBUM = 'FETCH_SINGLE_ALBUM';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const LOADING_ALBUMS = 'LOADING_ALBUMS';
export const LOADING_ALBUMS_FAILED = 'LOADING_ALBUMS_FAILED';
